<a href="https://colab.research.google.com/github/rajeshnayak23/RAJESHNAYAK_2001206023_AIML/blob/main/03_10_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class base:
  def add(self,a,b):
    return a+b
class derived(base):
  def mul(self,a,b):
    return a*b
m=int(input("a="))
n=int(input("b="))
obj=derived()
print(obj.add(m,n))
print(obj.mul(m,n))

a=9
b=7
16
63


In [9]:
#wap using multilevel inheritance to develop a calculator which contains four derived of derived class and only one child class
class cls1:
  def add(self,a,b):
    return a+b
class cls2(cls1):
  def sub(self,a,b):
    return a-b
class cls3(cls2):
  def mul(self,a,b):
    return a*b
class cls4(cls3):
  def div(self,a,b):
    return a/b
class cls5(cls4):
  def rem(self,a,b):
    return a%b
m=int(input("a = "))
n=int(input("b = "))
obj=cls5()
print("a+b=",obj.add(m,n))
print(obj.sub(m,n))
print(obj.mul(m,n))
print(obj.div(m,n))
print(obj.rem(m,n))

b = 4
a+b= 14
6
40
2.5
2


In [ ]:
class cls1:
  def add(self,a,b):
    return a+b
class cls2:
  def sub(self,a,b):
    return a-b
class cls3:
  def mul(self,a,b):
    return a*b
class cls4:
  def div(self,a,b):
    return a/b
class cls5(cls1,cls2,cls3,cls4):
  def rem(self,a,b):
    return a%b
m=int(input("a = "))
n=int(input("b = "))
obj=cls5()
print(obj.add(m,n))
print(obj.sub(m,n))
print(obj.mul(m,n))
print(obj.div(m,n))
print(obj.rem(m,n))


a = 20
b = 10
30
10
200
2.0
0


In [ ]:
#write apython program to input employee informations employee id ,name,basic salary ,hra=15 % ,ta=5% and medical allowence=5% if basic salary is 5000 and if 10% more than 10000
#usig single inheritance the base class contains all the informations but the derived contains the net saalry of aemployee with all informations.


In [13]:
import numpy as np
print(np.__version__)

1.22.4


In [12]:
import numpy
list=[10,20,30,40,50]
arr=numpy.array(list)
print(arr)


[10 20 30 40 50]


In [14]:
import numpy as numpy
list=[[10,20,30],[40,50,60]]
arr=np.array(list)
print(arr)


[[10 20 30]
 [40 50 60]]


In [15]:
import numpy as numpy
list=[[10,20,30],[40,50,60]]
arr=np.array(list)
print(arr[1])

[40 50 60]


In [16]:
import numpy as numpy
list=[[10,20,30],[40,50,60]]
arr=np.array(list)
print(arr[1][1])

50


In [21]:
import numpy as numpy
list=[[[1,2,3],[4,5,6],[7,8,9]]]
arr=np.array(list)
print("3D array is ",arr)

3D array is  [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [20]:
import numpy as np
list=[10,20,30,40,50,60]
arr=numpy.array(list)
print('Element')
for ele in arr:
  print(ele*2)

Element
20
40
60
80
100
120


In [22]:
import numpy as np
ndArray=np.array([1,2,3,4],ndmin=6)
print(ndArray)
print('Dimesion of array',ndArray.ndim)

[[[[[[1 2 3 4]]]]]]
Dimesion of array 6
